;;;; packages/javascript/src/runtime-method-resolver-tables.lisp — JS method tables

(in-package :cl-cc/javascript)

(defparameter *js-array-method-table*
  (list (cons "push" #'%js-array-push)         (cons "pop" #'%js-array-pop)
        (cons "shift" #'%js-array-shift)        (cons "unshift" #'%js-array-unshift)
        (cons "map" #'%js-array-map)            (cons "forEach" #'%js-array-for-each)
        (cons "filter" #'%js-array-filter)      (cons "reduce" #'%js-array-reduce)
        (cons "reduceRight" #'%js-array-reduce-right)
        (cons "find" #'%js-array-find)          (cons "findIndex" #'%js-array-find-index)
        (cons "some" #'%js-array-some)          (cons "every" #'%js-array-every)
        (cons "includes" #'%js-array-includes)  (cons "indexOf" #'%js-array-index-of)
        (cons "lastIndexOf" #'%js-array-last-index-of)
        (cons "join" #'%js-array-join)          (cons "slice" #'%js-array-slice)
        (cons "splice" #'%js-array-splice)      (cons "concat" #'%js-array-concat)
        (cons "reverse" #'%js-array-reverse)    (cons "sort" #'%js-array-sort)
        (cons "flat" #'%js-array-flat)          (cons "flatMap" #'%js-array-flat-map)
        (cons "fill" #'%js-array-fill)          (cons "copyWithin" #'%js-array-copy-within)
        (cons "entries" #'%js-array-entries)    (cons "keys" #'%js-array-keys)
        (cons "values" #'%js-vec-to-iter)
        (cons "@@iterator" #'%js-vec-to-iter)
        (cons "group" #'%js-array-group)
        (cons "groupToMap" #'%js-array-group-to-map)
        (cons "toReversed" #'%js-array-to-reversed)
        (cons "toSorted" #'%js-array-to-sorted)
        (cons "toSpliced" #'%js-array-to-spliced)
        (cons "with" #'%js-array-with)
        (cons "findLast" #'%js-array-find-last)
        (cons "findLastIndex" #'%js-array-find-last-index)
        (cons "at" #'%js-array-at))
  "Alist: JS Array.prototype method name -> host helper (receiver = first arg).")

(defparameter *js-string-method-table*
  (list (cons "slice" #'%js-string-slice)         (cons "indexOf" #'%js-string-index-of)
        (cons "lastIndexOf" #'%js-string-last-index-of)
        (cons "includes" #'%js-string-includes)   (cons "startsWith" #'%js-string-starts-with)
        (cons "endsWith" #'%js-string-ends-with)  (cons "split" #'%js-string-split-regex)
        (cons "replace" #'%js-string-replace-regex)
        (cons "replaceAll" #'%js-string-replace-all-regex)
        (cons "padStart" #'%js-string-pad-start)  (cons "padEnd" #'%js-string-pad-end)
        (cons "at" #'%js-string-at)               (cons "repeat" #'%js-string-repeat)
        (cons "charAt" #'%js-string-char-at)      (cons "charCodeAt" #'%js-string-char-code-at)
        (cons "concat" #'%js-string-concat)       (cons "match" #'%js-string-match-regex)
        (cons "matchAll" #'%js-string-match-all-regex)
        (cons "search" #'%js-string-search-regex)
        (cons "toUpperCase" #'%js-string-to-upper-case)
        (cons "toLowerCase" #'%js-string-to-lower-case)
        (cons "trim" #'%js-string-trim)           (cons "trimStart" #'%js-string-trim-start)
        (cons "trimEnd" #'%js-string-trim-end)
        (cons "codePointAt" #'%js-string-code-point-at)
        (cons "normalize" #'%js-string-normalize)
        (cons "substring" #'%js-string-substring)
        (cons "valueOf" (lambda (s) s))
        (cons "toString" (lambda (s) s))
        (cons "toWellFormed" #'%js-string-to-well-formed)
        (cons "isWellFormed" #'%js-string-is-well-formed)
        (cons "toLocaleLowerCase" #'%js-string-to-locale-lower-case)
        (cons "toLocaleUpperCase" #'%js-string-to-locale-upper-case)
        (cons "localeCompare" #'%js-string-locale-compare)
        (cons "@@iterator" #'%js-string-char-iter))
  "Alist: JS String.prototype method name -> host helper (receiver = first arg).")

(defparameter *js-set-method-table*
  (list (cons "add" #'%js-set-add)
        (cons "delete" #'%js-set-delete)
        (cons "has" #'%js-set-has)
        (cons "clear" #'%js-set-clear)
        (cons "forEach" #'%js-set-for-each)
        (cons "keys" #'%js-set-keys)
        (cons "values" #'%js-set-keys)
        (cons "entries" #'%js-set-entries)
        (cons "union" #'%js-set-union)
        (cons "intersection" #'%js-set-intersection)
        (cons "difference" #'%js-set-difference)
        (cons "symmetricDifference" #'%js-set-symmetric-difference)
        (cons "isSubsetOf" #'%js-set-is-subset-of)
        (cons "isSupersetOf" #'%js-set-is-superset-of)
        (cons "isDisjointFrom" #'%js-set-is-disjoint-from))
  "Alist: JS Set.prototype method name -> host helper.")

(defparameter *js-map-method-table*
  (list (cons "set" #'%js-map-set)
        (cons "get" #'%js-map-get)
        (cons "has" #'%js-map-has)
        (cons "delete" #'%js-map-delete)
        (cons "clear" #'%js-map-clear)
        (cons "getOrInsert" #'%js-map-get-or-insert)
        (cons "getOrInsertComputed" #'%js-map-get-or-insert-computed)
        (cons "forEach" #'%js-map-for-each)
        (cons "keys" #'%js-map-keys)
        (cons "values" #'%js-map-values)
        (cons "entries" #'%js-map-entries))
  "Alist: JS Map.prototype method name -> host helper.")

(defparameter *js-weak-map-method-table*
  (list (cons "set" #'%js-weak-map-set)
        (cons "get" #'%js-weak-map-get)
        (cons "has" #'%js-weak-map-has)
        (cons "delete" #'%js-weak-map-delete)
        (cons "getOrInsert" #'%js-weak-map-get-or-insert)
        (cons "getOrInsertComputed" #'%js-weak-map-get-or-insert-computed))
  "Alist: JS WeakMap.prototype method name -> host helper.")

(defparameter *js-weak-set-method-table*
  (list (cons "add" #'%js-weak-set-add)
        (cons "has" #'%js-weak-set-has)
        (cons "delete" #'%js-weak-set-delete))
  "Alist: JS WeakSet.prototype method name -> host helper.")

(defparameter *js-finalization-registry-method-table*
  (list (cons "register" #'%js-finreg-register)
        (cons "unregister" #'%js-finreg-unregister))
  "Alist: JS FinalizationRegistry.prototype method name -> host helper.")


(defparameter *js-number-method-table*
  (list (cons "toFixed"
              (lambda (n digits)
                (let ((d (if (eq digits +js-undefined+) 0 (truncate (%js-to-number digits)))))
                  (%js-strip-trailing-dot (format nil "~,vF" d (%js-to-number n))))))
        (cons "toString"
              (lambda (n &optional (radix 10))
                (let ((r (if (eq radix +js-undefined+) 10 (truncate (%js-to-number radix))))
                      (ni (truncate (%js-to-number n))))
                  (if (= r 10)
                      (%js-to-string n)
                      (string-downcase (format nil "~vR" r ni))))))
        (cons "toPrecision"
              (lambda (n prec)
                (if (eq prec +js-undefined+)
                    (format nil "~A" (%js-to-number n))
                    (%js-number-to-precision (%js-to-number n) (truncate (%js-to-number prec))))))
        (cons "toExponential"
              (lambda (n &optional digits)
                (let* ((v (%js-to-number n))
                       (d (if (or (null digits) (eq digits +js-undefined+))
                              6 (truncate (%js-to-number digits)))))
                  (format nil "~,v,,,,,'eE" d (coerce v 'double-float)))))
        (cons "valueOf" (lambda (n) (%js-to-number n)))
        (cons "toLocaleString" (lambda (n &rest _) (declare (ignore _))
                                 (format nil "~A" (%js-to-number n)))))
  "Alist: Number.prototype method name -> helpers.")

(defparameter *js-symbol-method-table*
  (list (cons "toString" #'%js-symbol-to-string)
        (cons "valueOf" (lambda (s) s)))
  "Alist: Symbol.prototype method name -> helpers.")
